### ISSUE TITLE
Just Suggestion Not Issue

### ISSUE THREAD

**Issue by elsahy22** [Xposed-Modules-Repo/app.neonorbit.chatheadenabler#1]
Can You Convert this Xposed module to Magisk module To avoid the problems of Riru and Zygisk

**Comment by NeonOrbit** [comment]
What kind of problem are you talking about?

**Comment by elsahy22** [comment]
When I Use Hide my App List It Make Some Apps Crash Like net cut and snap tube  and other apps when i remove riru or disable zygisk every things work fine

**Comment by NeonOrbit** [comment]
Do not use ``riru`` or ``hide my app list``. Use zygisk and whatever apps you need to hide, add them into zygisk denylist. 

As for your suggestion, no I can't convert this into magisk module. It needs art hook to dynamically alter messenger codes, simple magisk module would be messy in that case.

**Comment by elsahy22** [comment]
zygisk is detected by some Banking apps For this I use hide my app list

But I have another suggestion that the module should not be responsible for Messenger only, but it is better to facilitate work on it. It is possible to include the system as a whole as an idea similar to Backport for all devices use android 11+

**Comment by NeonOrbit** [comment]
> zygisk is detected by some Banking apps For this I use hide my app list

You should ask in LSPosed related groups, they might have a solution for you. 

> But I have another suggestion that the module should not be responsible for Messenger only

ChatHead is messenger's internal feature, it doesn't exist in any other apps. This module simply enables the feature, so the idea of backporting it for the whole system is scary.  ☠️
